export default [
    { "name": "Iwate", "kanji":  "岩手", "id": "JP-03",},
    { "name": "Miyagi", "kanji": "宮城", "id": "JP-04",},
    { "name": "Akita", "kanji": "秋田", "id": "JP-05",},
    { "name": "Gunma", "kanji": "群馬", "id": "JP-10",},
    { "name": "Ishikawa", "kanji": "石川", "id": "JP-17",},
    { "name": "Hyogo", "kanji": "兵庫", "id": "JP-28",},
    { "name": "Fukuoka", "kanji": "福岡", "id": "JP-40",},
    { "name": "Hiroshima", "kanji": "広島", "id": "JP-34",},
    { "name": "Kanagawa", "kanji": "神奈川", "id": "JP-14",},
    { "name": "Tokyo", "kanji": "東京", "id": "JP-13",},
    { "name": "Toyama", "kanji": "富山", "id": "JP-16",},
    { "name": "Saitama", "kanji": "埼玉", "id": "JP-11",},
    { "name": "Nagano", "kanji": "長野", "id": "JP-20",},
    { "name": "Shizuoka", "kanji": "静岡", "id": "JP-22",},
    { "name": "Aichi", "kanji": "愛知", "id": "JP-23",},
    { "name": "Kyoto", "kanji": "京都", "id": "JP-26",},
    { "name": "Osaka", "kanji": "大阪", "id": "JP-27",},
    { "name": "Nara", "kanji": "奈良", "id": "JP-29",},
    { "name": "Okinawa", "kanji": "沖縄", "id": "JP-47",},
]
